_target_: components.noise_generator.NoiseGenerator

modus: "inno"
additive: True
multiplicative:  False
time_dependent:  False
autoregressive:  False
common: False
semi_synthetic: False
shock: False
shock_proba:  0.05
time_dependent_cycle: "mean_var_shift" # Defaults to yearly cycle. other callable can be provided.
shock_size: 5
snr: Null
non_additive_noise_proba: 0
autoregressive_innovation: 0.5
non_gaussian_additive: 0.0
non_equal_variance_range: False
scale_for_time_dependent: 0.005
which_non_gaussian: "weibull"
semi_synthetic_noise_path: "tools_and_examples/semi_synthetic_bases/"