defaults:
  - _self_
  - method: var

# We use the full formatting for TCD-Arena data here even if its overkill.
data_base_path: "sample_datasets/"
ds_name: "no_violation_small" # folder name for datasets
data_path: ${data_base_path}${ds_name}
which_dataset: 0 # index of which dataset to use in the folder
verbose: 1
